# Enter domain name:
int_domain_name: "tinotest.com"
# variables for all systems
dns_domain_name: "tinotest.com"

# variables for logging system
logging_docker_ce_version: " docker-ce=5:28.4.0-1~ubuntu.24.04~noble"
logging_docker_compose_version: "v2.10.0"

# For next vars DNS have to be set
# Set kibana url
kibana_url: kibana.tinotest.com

# Enter packages version:
# docker
docker_ce_version: docker-ce=5:28.4.0-1~ubuntu.24.04~noble
docker_compose_version: v2.18.1
docker_node_exporter_version: v1.5.0
docker_cadvisor_version: v0.47.0
docker_nginx_version: 1.29.1
# pip
pip_docker_version: 6.1.3
pip_docker_compose_version: 1.29.2
# elastic
elk_version: 9.0.7
