---
# Installs logging cluster outside K8s, controlled with tags:
  # add_elasticsearch
  # add_kibana
  # add_fleet
  # kibana_config_changed
- name: Installing logging role
  hosts: logging_cluster
  gather_facts: true
  roles:
    - { role: roles/logging }
  become: yes
  become_user: root
