---
# # Configure ansible ssh access from central bastion server to nodes in inventory
# - name: Configure ssh for Instance(s)
#   hosts: all
#   remote_user: tino
#   gather_facts: false
#   tasks:
#     - name: Import tasks
#       import_tasks: roles/provision/tasks/set-ssh-key.yml
#       tags: set-ssh-keys
#   become: yes
#   become_user: root

# Installs users ssh public keys, updates ntp with google timeservers, updates OS
# If new users ssh public keys needs to be added you can run this role with tag: set_users_ssh_key
- name: Run provision role
  hosts: all
  remote_user: tino
  gather_facts: true
  roles:
    - { role: roles/provision }
  become: yes
  become_user: root
