---
- name: Register elastic CA
  command: cat /var/containers/logging/certs/tino-root.crt
  register: ca_register
  delegate_to: "{{ groups['logging_cluster'][0] }}"

- name: Copy kibana.yml to kibana server
  template:
    src: kibana.j2
    dest: /var/containers/logging/extra/kibana.yml
    owner: 1000
    group: 0
    mode: g=rwx
  tags: kibana_config_changed

# #ovo ispod taskovi failaju na mojoj masini a trebali bi proci : stavim password ovak : https://www.elastic.co/guide/en/elasticsearch/reference/current/reset-password.html
# - name: Exec to elastic container and generate kibana pass
#   community.docker.docker_container_exec:
#     container: elasticsearch
#     command: '/usr/bin/curl -s -X POST --cacert /usr/share/elasticsearch/config/certificates/tino-fullchain.crt -u elastic:{{elastic_password}} -H "Content-Type: application/json" https://{{ansible_hostname}}.{{int_domain_name}}:9200/_security/user/kibana_system/_password -d "{\"password\":\"{{kibana_password}}\"}"'
#   when: inventory_hostname in groups['logging_cluster'][0]

# #Running this because for some reason kibana break if the password isn't reset
# - name: Exec to elastic container and reset elastic password
#   community.docker.docker_container_exec:
#     container: elasticsearch
#     command: '/usr/bin/curl -s -X POST --cacert /usr/share/elasticsearch/config/certificates/tino-fullchain.crt -u elastic:{{elastic_password}} -H "Content-Type: application/json" https://{{ansible_hostname}}.{{int_domain_name}}:9200/_security/user/elastic/_password -d "{\"password\":\"{{elastic_password}}\"}"'
#   when: inventory_hostname in groups['logging_cluster'][0]

- name: Restart elastic service after resetting password
  community.docker.docker_compose:
    project_src: /var/containers
    services: 
      - elasticsearch
    restarted: true

- name: Wait for port 9200 to become open on the host, don't start checking for 20 seconds
  wait_for:
    port: 9200
    delay: 20
  when: inventory_hostname in groups['logging_cluster'][0]

- name: Create and start kibana service
  community.docker.docker_compose:
    project_src: /var/containers
    services: kibana

# - name: Restart kibana service after configuration change
#   community.docker.docker_compose:
#     project_src: /var/containers
#     services: 
#       - kibana
#     restarted: true
#   tags: ['never', 'kibana_config_changed']
